### ISSUE TITLE
Looking forward to the code and data release

### ISSUE THREAD

**Issue by blmoistawinde** [thongnt99/acl22-depression-phq9#1]
Hi, I'm Zhiling Zhang from SJTU, recently studying the task of depression detection from online text. I just got [one paper accepted by IJCAI 2022](https://github.com/blmoistawinde/scale_early_depress_detect/blob/main/paper.pdf), and hopes to make further works on this topic. 

I've read the arxiv version of your ACL22 paper, and found the idea of leveraging PHQ-9 symptoms to improve the interpretability and generalizability of depression detection especially inspiring. So I cannot wait to see your full code (Questionnaire, depression model and dataset heuristics) release here. Thanks!

**Comment by thongnt99** [comment]
Hi, 
Thanks for your interest. 
The patterns and code will be released soon. I will notify you when it's ready. 

Best, 
Thong

**Comment by tsw-1** [comment]
> 

嗨，您好。我是一名研一萌新，也是NLP方向的。最近阅读了此篇论文，非常震撼和感兴趣。所以想结合代码一起研究。想问一下您跑通这个代码了吗

**Comment by tsw-1** [comment]
> Hi, I'm Zhiling Zhang from SJTU, recently studying the task of depression detection from online text. I just got [one paper accepted by IJCAI 2022](https://github.com/blmoistawinde/scale_early_depress_detect/blob/main/paper.pdf), and hopes to make further works on this topic.
> 
> I've read the arxiv version of your ACL22 paper, and found the idea of leveraging PHQ-9 symptoms to improve the interpretability and generalizability of depression detection especially inspiring. So I cannot wait to see your full code (Questionnaire, depression model and dataset heuristics) release here. Thanks!

我感觉注释和说明有点少，应该是我太菜了。想请问一下有没有更详细一点的使用文档呢，非常感谢！

**Comment by thongnt99** [comment]
I am happy to discuss and answer your questions @tsw-1 
You can  also contact with me via email: nguyenthacthong@gmail.com
