### ISSUE TITLE
'neg_map' for negating posts

### ISSUE THREAD

**Issue by Jantory** [thongnt99/acl22-depression-phq9#2]
Hi Thong,
I am currently working on reproducing the experimental result shown in your paper. However, when I try to run your code, I notice the mapping files for negating posts with different symptoms are missing. Maybe it is a big ask, but could you please share those files as well?

Many thanks in advance!
Best,
Zeyu

**Comment by thongnt99** [comment]
Hi @Jantory , You can have a look at this [file](https://github.com/thongnt99/acl22-depression-phq9/blob/main/resources/patterns/negation_templates.txt)
